services:
  cashlink-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cashlink-api
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal;Database=CashLinkDB;User Id=sa;Password=Password123!;TrustServerCertificate=True;MultipleActiveResultSets=true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped